### ISSUE TITLE
Distance - Egypt to Jordan

### ISSUE THREAD

**Issue by Ian-AC** [the-abe-train/globle#100]
Game today (27/05/2022) had the distance of the mystery country from Egypt as 45km. The mystery country turned out to be Jordan. Measuring the distance on the map, it appears that the distance is only 7.4km (Taba in Egypt at the Israel border to the container port at Aqaba in Jordan). See attached screenshot. Perhaps a review of the distance data is required.

[Screenshot 2022-05-27.pdf](https://github.com/the-abe-train/globle/files/8784785/Screenshot.2022-05-27.pdf)

By the way, this is an excellent brain game and half my extended family is playing it daily.

**Comment by epixian** [comment]
> These issues arise from the game's borders not being perfectly precise or accurate. I'm pushing an update in the next day or so that just rounds borders to the nearest 50 km or 50 miles.
My siblings and mom and I all play against each other daily and have come to expect a certain level of inaccuracy.  Instead of reducing inaccuracies, this solution seems to... standardize them?  I foresee quite a bit of backlash there.
