### ISSUE TITLE
Russia doesn’t share a border with Azaerbaijan

### ISSUE THREAD

**Issue by The11thaardvark** [the-abe-train/globle#102]
![74440DA3-B982-4AB9-BC7F-F2FAB59DA239](https://user-images.githubusercontent.com/106516464/170950173-cc2d4e4f-26e9-4fb6-9f24-3486f9ea49ef.png)

as best I know Russia doesn’t share a border with Azerbaijan like your game says it does.

**Comment by the-abe-train** [comment]
I believe it does actually, at least according to Google Maps.

![image](https://user-images.githubusercontent.com/47761569/171029071-809458f2-7b9f-4b48-af4d-0a03a97e8bf6.png)

**Comment by The11thaardvark** [comment]
Opps sorry!
