### ISSUE TITLE
Today's Answer Distance Issue

### ISSUE THREAD

**Issue by jasonhischier** [the-abe-train/globle#109]
There is a border shared by France and Andorra, but the app indicated the distance as "< 10km" instead of 0, as expected. See screenshot of the issue:

![IMG_20220603_222843](https://user-images.githubusercontent.com/9277623/171979076-40e5dd85-6322-44ed-bfcd-084795a77077.png)

**Comment by epixian** [comment]
This was intentional in the last update.  See #104

**Comment by jasonhischier** [comment]
I see, thanks!
