### ISSUE TITLE
Directional Gradient Clues

### ISSUE THREAD

**Issue by noahwill** [the-abe-train/globle#11]
I would love to see a mode where countries get a subtle gradient in the direction (N, S, E, W) of the correct guess - it can be a bit brutal getting in areas that have a lot of countries bouncing around until I find the right direction to go. A mode like this would be really sastisfying! 

The cardinal directions would be great, it would probably make it too easy if the gradients were set on degrees pointing directly at the solution.

**Comment by the-abe-train** [comment]
This is an interesting idea, maybe something for an easier mode in the game, but I don't have any plans for this at the moment.
