### ISSUE TITLE
More leeway with country names, please

### ISSUE THREAD

**Issue by mstephans** [the-abe-train/globle#12]
I really appreciate that you take DRC as an input. I’d love some of that leeway on St vs Saint as well as trailing spaces. There is another globe style game that uses a drop down for entries, which I think would work well. I do like guessing the names, but getting “Invalid country” because I can’t spell Turkmenistan (thanks autocorrect!) limits me to phone usage. 

Oh, and a deeper Zoom would be great, even just using a +/- setup in the corner. 

This is a must play for me daily, thanks for creating it!!

**Comment by the-abe-train** [comment]
- I just pushed a change that will allow "St." or "st." in place of "Saint" for all countries with Saint in the name. 
- Trailing spaces are already trimmed for all guesses. 
- I don't have library of common misspellings for difficult country names, and I'm also not too concerned with people learning how to spell them by going to Google.
- I'm considering adding +/- zoom buttons as part of an accessibility update to the game, but I don't have the details for that worked out yet.

Thank you for playing!

**Comment by waldyrious** [comment]
> I don't have library of common misspellings for difficult country names, and I'm also not too concerned with people learning how to spell them by going to Google.

There are some suggestions for this in #15, by the way :)
