### ISSUE TITLE
Kiribati geometry is wrong (or at least incomplete)

### ISSUE THREAD

**Issue by rummelsworth** [the-abe-train/globle#127]
The game's current geometry for Kiribati only shows Kiritimati or some other island way out in the east part of Kiribati, not the "main" islands 2000 miles west (where the capitol is located). The distance calculation seems to be using the wrong geometry anyway. (Today's country was Nauru, so yeah, this matters/mattered to me, lol)

Other countries seem to be affected too, like Micronesia and the Marshalls.

**Comment by Ivan-Adriazola** [comment]
Im pretty sure all the countries in Oceania have some issues, todays guess was tonnga but New Zealand guess was shown closer than Tuvalu (according to the color code) im guessing this has to do with first FAQ answer:

"Distance between countries is defined as the minimum distance between their land borders along the Earth's surface. Territories (areas that appear in gray when their parent country is guessed) and water borders are not included in distance calculations."

and by some weird logic newzealand shares border with Tonga more than it does with Tuvalu

there is also the issue of visibility but thats for another thread

**Comment by rummelsworth** [comment]
Today's guess was Kiribati, and the effect of the incorrect geometry is visually dramatic.

In the screenshot below, You can see that Fiji and (less clearly) the Marshall Islands have been guessed. The circle annotation is over the "main islands" of Kiribati including the capital, Tarawa. The X annotation is over the app's only geometry of Kiribati, i.e. the far eastern portion of Kiribati, seemingly just Kiritimati.

I've highlighted the distance ranking below the globe, where you can see that Fiji is considered closer than the Marshalls. In reality, it isn't closer, not by a long shot. The Marshalls are way closer to the main islands of Kiribati, and this is a bit frustrating for a user. Well, for me anyway 😅

<img src="https://user-images.githubusercontent.com/3069355/191125926-9b6b3958-72f2-40d1-92de-ee94abc76787.png" height=300px />

The first FAQ answer doesn't really help to explain Kiribati's geometry. This is like if France's geometry was only the island of Corsica and didn't include continental France.

Agreed on visibility, but the app does a decent job by raising guessed countries "up" from the sphere.

**Comment by the-abe-train** [comment]
Kiribati is now 3 islands in the game.
