### ISSUE TITLE
mistakes in polish tranlation

### ISSUE THREAD

**Issue by WBurzynski** [the-abe-train/globle#128]
Georgia is translated as "Abchazja", which wrong and should be corrected to "Gruzja". When guessing China it would be convinent to use not only full name "Chińska Republika Ludowa ", but commonly used "Chiny". I'm sure there are more mistakes that i'm yet to encounter.

I'm willing to do a PR, but i don't know where are translation files.

**Comment by the-abe-train** [comment]
Added the names you provided as "alternative names". Will merge changes shortly.
