### ISSUE TITLE
No mystery country? 

### ISSUE THREAD

**Issue by wildernesswill** [the-abe-train/globle#130]
![7C697A29-FDFB-4A09-8CF6-B9DF09DA5039](https://user-images.githubusercontent.com/17561172/177054299-170de773-68c0-4b49-99ed-ddf6f40f39ef.png)

Based on the mileage and colors I cannot determine the mystery country. Am I missing something, or is there a bug in today’s 7/3/2022.

**Comment by the-abe-train** [comment]
It's a tough one, but there's no big.

**Comment by the-abe-train** [comment]
It's a tough one, but there's no bug.

**Comment by wildernesswill** [comment]
Thanks! Maldives. My bad.
