### ISSUE TITLE
Latest commit broke it

### ISSUE THREAD

**Issue by stevenorum** [the-abe-train/globle#133]
Looks like https://github.com/the-abe-train/globle/commit/28026e6ce39a3bbf6abba1eef71d1ddba1c9cc1a broke the site:

When trying to submit a guess, nothing happens and the following is in the console:

react-dom.production.min.js:101 Uncaught TypeError: Cannot read properties of undefined (reading 'en-CA')
    at Guesser.tsx:69:25
    at onSubmit (Guesser.tsx:102:24)
    at Object.Wl (react-dom.production.min.js:52:317)
    at ql (react-dom.production.min.js:52:471)
    at react-dom.production.min.js:53:35
    at La (react-dom.production.min.js:100:68)
    at Ta (react-dom.production.min.js:101:380)
    at react-dom.production.min.js:113:65
    at wl (react-dom.production.min.js:292:189)
    at react-dom.production.min.js:50:57

**Comment by glend21** [comment]
Same (lack of) behaviour for me. 

Tested on Firefox 100.0 and Chrome 103.0.5060.66

**Comment by kevalii** [comment]
I think this is related to a change in how `alternateNames` is imported in `Guesser.tsx` https://github.com/the-abe-train/globle/blob/28026e6ce39a3bbf6abba1eef71d1ddba1c9cc1a/src/components/Guesser.tsx#L13-L14

`alternate_names.json` doesn't feature a property named `features`. I think this was inadvertently copied over from the import right above for `countryData`

https://github.com/the-abe-train/globle/blob/28026e6ce39a3bbf6abba1eef71d1ddba1c9cc1a/src/components/Guesser.tsx#L12

**Comment by the-abe-train** [comment]
Sorry about that. Should be working now!
