### ISSUE TITLE
List of countries 

### ISSUE THREAD

**Issue by rhinoredondo** [the-abe-train/globle#139]
Check out Worldle. When you start to write the answer, choices that match pop up. You don’t have to wonder what’s on Globle’s list of countries. Your game is too frustrating.

**Comment by the-abe-train** [comment]
Not going to add a dropdown list, but open to spellchecker. Please comment on PR #101 if you are interested in that feature.

**Comment by rhinoredondo** [comment]
A dropdown list would look so much more professional.
    On Thursday, October 20, 2022 at 07:40:44 PM EDT, Abe Train ***@***.***> wrote:  
 
 


Not going to add a dropdown list, but open to spellchecker. Please comment on PR #101 if you are interested in that feature.
