### ISSUE TITLE
Ads steal focus, prevent user input

### ISSUE THREAD

**Issue by cha4les** [the-abe-train/globle#148]
Hi there, I love Globle and I play every day!

Today I’m not able to play, because a Best Buy ad keeps popping up and greying out the game elements. Dismissing the ad does make the ad go away, but the game elements remain in a disabled state. If I refresh the page, there is a brief period (about 1 second) where I can select the text box or rotate the globe, but then they become disabled again.

I’m playing on an iPad Air 3rd generation with iOS 15.6.1, using the Safari browser.

**Comment by the-abe-train** [comment]
Hey @cha4les , I'm really sorry about that. Can you share a screenshot of the ad so I can tell my ad provider to make sure we don't show it again?

**Comment by cha4les** [comment]
Hi, thanks for the quick response! Here is a screen shot. (I was able to complete the game by typing very quickly!)

[image]

On Nov 27, 2022, at 8:34 AM, Abe Train ***@***.***> wrote:

﻿

Hey @cha4les<https://github.com/cha4les> , I'm really sorry about that. Can you share a screenshot of the ad so I can tell my ad provider to make sure we don't show it again?

**Comment by cha4les** [comment]
Hi @the-abe-train, I sent a screenshot via email. Thanks!

**Comment by the-abe-train** [comment]
My ad partner assures me that they've blocked that vendor for now and are looking into it.

**Comment by cha4les** [comment]
Everything seems to work fine again on my end. Thanks again for the quick resolution!
