### ISSUE TITLE
Mispellings

### ISSUE THREAD

**Issue by jaoxford** [the-abe-train/globle#15]
I think this game is great! Thanks for creating it.

As for the actual issue:
I think slight mispellings should be accepted.

For example I had typed `kyrzgystan` and the correct spelling is `kyrgyzstan`. Could there be some way of checking for countries that are slightly misspelt, or some kind of hinting mechanism?

**Comment by IanDLacy** [comment]
I think someone on another issue suggested some kind of suggestion|completion mechanism similar to the kind of 'automatic drop down' things you see around. I don't think misspellings should be accepted, but I think some mechanism as described would be a nice convenience feature.

**Comment by waldyrious** [comment]
There could be a list of known aliases, for example based on [Wikipedia redirects to the country article](https://en.wikipedia.org/w/index.php?title=Special:WhatLinksHere/Kyrgyzstan&hidetrans=1&hidelinks=1&limit=100) (excluding redirects to sections), which would have the benefit of including alternative valid names, besides common mispellings.

**Comment by jaoxford** [comment]
> There could be a list of known aliases, for example based on [Wikipedia redirects to the country article](https://en.wikipedia.org/w/index.php?title=Special:WhatLinksHere/Kyrgyzstan&hidetrans=1&hidelinks=1&limit=100) (excluding redirects to sections), which would have the benefit of including alternative valid names, besides common mispellings.

Something along these lines is a good idea.

**Comment by zerdip** [comment]
Awesome game. 
Greenland is invalid?
England is invalid? (Shows as UK)

**Comment by cornzz** [comment]
> Awesome game. Greenland is invalid? England is invalid? (Shows as UK)

Greenland is not its own country, its part of Denkmark.
England is a country but doesn't have its own government and is usually just regarded as part of the UK, just like the other parts of UK.

**Comment by the-abe-train** [comment]
Closing this thread to move the discussion of spelling corrections to PR #101
