### ISSUE TITLE
Unescaped backtick in `Game4` Message (Chrome, Android)

### ISSUE THREAD

**Issue by wimdavies** [the-abe-train/globle#157]
Hi there! First of all, thanks for making this game, I play it everyday — it's a lovely little part of my morning routine that I share with a friend, so thank you for all your hard work!

I've noticed a bug on mobile (Android 10; Chrome 115.0.5790.166) for quite a while: after I've guessed my first country and the message "Drag, tap, and zoom-in on the globe to help you find your next guess." is displayed, this message terminates in a backtick. Please see screenshot below.

I can see that the message in question is stored on line 44 of src/i18n/messages/en-CA.ts — I'm not sure how this gets processed, or where the buggy behaviour might be coming from. I don't know if you accept PRs from randomers, but if you do, I'd be happy to have a little look at least?

Thanks again.

<img src="https://github.com/the-abe-train/globle/assets/112558900/1290d0b0-1d33-4bdb-ab37-63ba9fb2a635" height=40% width=40%>

**Comment by the-abe-train** [comment]
This isn't the repo tied to the game anymore, but I fixed it in the game.
Thank you!!

**Comment by wimdavies** [comment]
Sorry, I didn't realise this isn't the active repo for the game. That's great that you fixed the issue! My pleasure, I'm glad I could make a contribution 😊
