### ISSUE TITLE
Cyprus, Greece Distance

### ISSUE THREAD

**Issue by PaoloRuben** [the-abe-train/globle#161]
Today playing on infinite mode I guessed Egypt 365 km from Greece no problem, but when guessig Cyprus the game said it was further away, that is wrong! Castellorizo (Greece) is 270 Km away from Cyprus

**Comment by the-abe-train** [comment]
Castellorizo is too small for the dataset, and so Globle considers it an exclave that does not count towards the distance calculation. I'm sorry for the confustion.
