### ISSUE TITLE
Wrong borders near Israel

### ISSUE THREAD

**Issue by shirzzz** [the-abe-train/globle#164]
Hello,
I was playing your game a couple of times and I was so disappointed of the mistake you made around Israel.

First of all, as a citizen of Israel I can promise you that there is no country named Palestine.
The green line you see on the map is not a border line it just show the achievements and changes of the land throughout the six days War on 1967.

The real map of Israel is: the union of " Plastine" and Israel in the game.

Please fix it 🙏 
In times like this where my country is under attack by a terror organization it is really painful to see someone thinks it is a country.

**Comment by the-abe-train** [comment]
I needed an objective source for the list of countries in the game, and went with this
https://www.sporcle.com/blog/2013/01/what-is-a-country/

I'm not going to stray from that now, but if you want to discuss further, feel free to send me an email at abe@trainwrecklabs.com
