### ISSUE TITLE
After reload the closest country is not first.

### ISSUE THREAD

**Issue by hasecilu** [the-abe-train/globle#19]
After a freeze (the globe does not rotate) I decided to reload the page but the list of countries were not updated according to the closest one, the list is only updated after a new country is entered. 
The showed order is the order in which you submitted them.
![Screenshot from 2022-02-13 13-24-06](https://user-images.githubusercontent.com/53124818/153771444-3846e47d-6b10-456e-8298-1cc7c28b4e48.png)
.

**Comment by the-abe-train** [comment]
I couldn't fix the freezing, that's caused by the globe's underlying library, but I was able to fix the reload order. Thank you for pointing that out! Try again and let me know if you run into any more issues.

**Comment by hasecilu** [comment]
I have just checked it and it is working, thanks for the fix!
