### ISSUE TITLE
Missing country names - please document source/authority for names and inclusion status

### ISSUE THREAD

**Issue by murdocha** [the-abe-train/globle#2]
This is a great implementation of the idea so far!

However, many smaller country names are missing including:

- Liechtenstein
- Andorra
- Monaco
- San Marino

some "countries" part of larger entities are not present:
- Scotland
- Wales
- Northern Ireland
- England

while other countries/territories that are part of other entities _are_ present:
- Greenland (but not under the indigenous Greenlandic name "Kalaallit Nunaat") which is a constituent part of the Kingdom of Denmark, along with the "Faroe Islands" (also not present).

Some countries have some "ambiguity" in their boundaries or sovereignty (claimed variously as independent or as occupied/integral territories of another country). Examples include:
- Tibet (not included)
- Hawaii (not included)
- Western Sahara (is included)

That's a complicated subject, but you should just add a disclaimer (in an "about" section) that you are following a particular authority/source for your country boundaries and criteria for inclusion (and document that source, even if it is just from Wikipedia). Same goes for documenting sources for "proper" internationally accepted names.

**Comment by IanDLacy** [comment]
Yeah, this would be good information to have for a number reasons.

Hawaii is firmly a US state though. Adding states and other equivalent entities would make for a good 'hard mode', however.

**Comment by the-abe-train** [comment]
Thank you for taking an interest in helping me improve the game! With these suggestions in mind, I adjusted borders and added countries in the update to v1.1.0 on Feb 4. The definition of "what is a country?" was borrowed from [Sporcle](https://www.sporcle.com/blog/2013/01/what-is-a-country/) and there is a link to it in the Help screen.
