### ISSUE TITLE
Distance in Km or degrees

### ISSUE THREAD

**Issue by alistaircarscadden** [the-abe-train/globle#21]
I have heard comments about colour issues in the game, and personally find it very difficult to discern what distance a specific shade may correspond with. I think it would be useful, and possibly necessary for accessibility for those with colour blindness, to have a mode or feature that shows the distance or amount of degrees a country is away from the answer.

**Comment by alistaircarscadden** [comment]
I didn't see the new colour blind option that heightens the countries and uses black and white. Thanks for implementing that. I think the suggestion here should still be considered though.

**Comment by the-abe-train** [comment]
I added the "closest border" indicator to the bottom of the game screen. I hope that helps.
