### ISSUE TITLE
Zoom into carribean more easily

### ISSUE THREAD

**Issue by alistaircarscadden** [the-abe-train/globle#22]
I find it very difficult to see the colour certain small countries have. Specifically ones like Europe: Andorra, Vatican and C.A.: St. Lucia, Grenada, etc.

For example (and because it's quite funny), here's Vatican (in night mode): 
![image](https://user-images.githubusercontent.com/7132621/154164262-be7e19e0-5543-4249-ad59-9c27b7eb1b9f.png)

On desktop I can use my scroll wheel to zoom all the way in like the picture above. However, on mobile it only allows me to zoom so far before it maxes out and un-zooms when I let go of the screen.

Some ideas:

* +/- arrows to allow zooming easily on mobile
* on the country list at the bottom of the screen adding a background with the corresponding colour so they can be seen there
* when an island country is guessed a specific zoom and position is moved to where the islands are all visible
* clicking a country at the bottom already positions to that country, but it could also zoom to a reasonable amount to see it clearly
* for countries smaller than X Km wide or Y Km^2 of area add a circle around them that has the correct colour

![image](https://user-images.githubusercontent.com/7132621/154164938-ef74be1e-eb3e-4ef0-8516-a7874ad4a2ae.png)

**Comment by the-abe-train** [comment]
Zooming in on the really small countries is still imperfect, but the latest update has automatic zooming in for small countries, and I believe that helps a lot. Also, +/- have been added for mobile. No other zooming changes planned.
