### ISSUE TITLE
Cloudflare Web Analytics

### ISSUE THREAD

**Issue by mu88** [the-abe-train/globle#23]
Thank you for your neat little game 👍🏻 

One question: when playing on https://globle-game.com, I see traffic to https://cloudflareinsights.com. Where can I find that particular code within your repo? Honestly it feels a bit suspicious that just this particular piece of code is missing...

Best regards!

**Comment by the-abe-train** [comment]
Hi there! The site uses CloudFlare Analytics, which is injected at hosting and thus does not appear anywhere in the code. It never occurred to me that this would look suspicious but I totally understand your point. To remedy this, I'm adding the text below to the README in my next update. I appreciate you pointing this out, and I will pay closer attention to how users perceive analytics and privacy with all my future apps and sites.

Globle is hosted by CloudFlare and tracks users with CloudFlare Web Analytics, a privacy-first analytics platform. The analytics are injected during hosting, so while you may see traffic to https://cloudflareinsights.com/ the script that sends information to CloudFlare is not anywhere in this repo. Click here to learn more about CloudFlare Web Analytics, [click here](https://www.cloudflare.com/en-gb/web-analytics/).

**Comment by mu88** [comment]
Thank you for taking my considerations into account! 🙏🏻
