### ISSUE TITLE
Missing countries

### ISSUE THREAD

**Issue by KatieGracieOrr** [the-abe-train/globle#28]
Hiya,

Nice game, I'm enjoying learning where some places are that I couldn't have easily placed before! My friend recommended it to me, however we noticed that our countries aren't on it - Scotland and Wales are countries, as is Northern Ireland, and England is also a separate country 😉

Cheers,
Katie

**Comment by darekkay** [comment]
As stated in the FAQ, this game uses [this list](https://www.sporcle.com/blog/2013/01/what-is-a-country/) as a reference.

> [England, Scotland, Wales, Northern Ireland](https://www.sporcle.com/blog/2017/12/is-england-a-country/):  While these four are referred to as countries in the United Kingdom and elsewhere, they are no more independent nations than the state of Texas or California. They don’t handle their own national defense or foreign relations, and they do not have a place in the U.N. outside of the UK.  These four countries are not included.

**Comment by KatieGracieOrr** [comment]
Oh waw! That's an unfortunately expressed statement on the sporcle page!
Anyway, never mind I guess there's not much point in arguing when there's an external reference list for the game.
