### ISSUE TITLE
Zoom Issues

### ISSUE THREAD

**Issue by lizzyd710** [the-abe-train/globle#35]
Hey, love the game! 

Sometimes when I zoom in on the globe, I can't zoom back out, and even when I move my mouse over to another country within the scope, the country name stays the same. If I enter a new country, it doesn't move the globe to show it, but if I refresh the page, it resets the view and I pick up where I left off.

**Comment by canerder** [comment]
I believe this the same issue as [Freezes when (i think) zooming in #39](https://github.com/the-abe-train/globle/issues/39).

**Comment by the-abe-train** [comment]
I'm gonna close this issue in favour of using #39 as the main issue for this problem given that there's more detail there.
