### ISSUE TITLE
Globle Unlimited

### ISSUE THREAD

**Issue by techpluscraft** [the-abe-train/globle#43]
A lot of people want to keep playing after they finish one so I was thinking maybe a level system or making it unlimited

**Comment by markkkkas** [comment]
+++ its soo addictive :D

**Comment by techpluscraft** [comment]
> +++ its soo addictive :D

Yes that’s why people wanna keep playing it

**Comment by techpluscraft** [comment]
> I actually quite like how there's one per day - it makes conversation between friends, and it makes you want to come back the next day; similar to wordle.

Maybe there could be two modes?

**Comment by the-abe-train** [comment]
What would everyone think of one main game per day, and then an unlimited mode that doesn't affect your score or streak?

**Comment by techpluscraft** [comment]
> What would everyone think of one main game per day, and then an unlimited mode that doesn't affect your score or streak?

I like that idea

**Comment by the-abe-train** [comment]
Resolved with Practice Mode
