### ISSUE TITLE
São Tomé e Príncipe 

### ISSUE THREAD

**Issue by ricardobananas** [the-abe-train/globle#44]
Hey there! Big fan of this game - it’s the first thing I do with my morning coffee.

Is there a chance that São Tomé e Príncipe is missing from the list of countries? I could swear the other day I tried it in both English and Portuguese and neither were accepted. Same for Cape Verde.

sorry I’m not very tech savvy so don’t know where the list of countries is saved.

thank you!

**Comment by willdebeast04** [comment]
Andorra as-well?

**Comment by olliechick** [comment]
It's under "São Tomé and Principe"; "STP", "Sao Tome and Principe" are also accepted.

I just checked and both "Cape Verde" and "Andorra" were accepted.

**Comment by ricardobananas** [comment]
Yeap just tested and it’s working!
