### ISSUE TITLE
Belize in wrong spot

### ISSUE THREAD

**Issue by TeresaBelize** [the-abe-train/globle#48]
Playing today’s globle and I guessed Belize and instead an island in the Galapagos lit up orange 🤔, Belize did not light up.
![7434F647-637C-4D5A-A448-D1FD9CF5127D](https://user-images.githubusercontent.com/101433547/157983866-19ffba3d-908e-49cf-8112-007c18f40951.png)
![45957139-214C-4C43-8E4F-156100FC6900](https://user-images.githubusercontent.com/101433547/157983895-4a2dc44b-9df8-48f7-8413-f649352b71b8.png)

**Comment by the-abe-train** [comment]
The Galapagos lit up because you guessed Ecuador, not Belize. Belize appears to be working normally.
![image](https://user-images.githubusercontent.com/47761569/160724050-5beff43c-6d08-44aa-ab18-31fef2ca29d8.png)
