### ISSUE TITLE
New design/style suggestion

### ISSUE THREAD

**Issue by albemala** [the-abe-train/globle#49]
First of all, thank you for making this game! I love it and I play it every day 😃 

I'm learning UI design and, as an exercise and for fun, I redesigned Globle. I don't want to impose anything on anyone. If you like the new design and would like to use it, great! If you just want to take some ideas from it, that's fine as well! If you don't like it or don't want to change the current design, no problem either. 😃 

With the new design, I wanted to create a playful experience while keeping a clean and nice style. My goal was also to give the game a stronger personality. The idea was to use some common design elements related to the earth: clouds, the sky, the sun, airplanes... The functionality is the same, except for a couple of small suggestions. Here's what I came up with.

# Help/Intro

![help](https://user-images.githubusercontent.com/2332860/158016708-1d94f826-6ccc-445c-8656-b13aab1e7db8.png)

# Game

**Suggestion**: make the answers a list instead of a grid. Also, add a small distance indicator next to each country (along with the flag).

![game](https://user-images.githubusercontent.com/2332860/158016716-40d8def6-9954-4c5b-a9ae-cdf1cde906f0.png)

# Victory

**Suggestion**: replace the country input field with the victory banner.

![victory](https://user-images.githubusercontent.com/2332860/158016722-2fd75b7c-2611-4020-82b8-a71c0bc39b79.png)

# Stats

I've made 2 versions of this screen, one that is more similar to the current one, and one with a different layout.

![stats-1](https://user-images.githubusercontent.com/2332860/158016728-e5ba9d3d-e6cc-460d-9e2e-af7b50c59dc1.png)

![stats-2](https://user-images.githubusercontent.com/2332860/158016732-30e0c614-c7e5-493a-b9d6-7311fac85528.png)

# Preferences

![preferences](https://user-images.githubusercontent.com/2332860/158016737-f0c1741f-0042-4da3-8d9b-146ed5edb6c6.png)

# Button states

![button-states](https://user-images.githubusercontent.com/2332860/158016741-d91148b4-5a45-46e7-9f37-7a37ba8dc390.png)

---

The re-design is not finished. There are a few things I'd like to revisit and see if I can improve. My next goal will be to make a desktop version and a dark-mode version as well.

I see you are already using Tailwind CSS to implement the game style. I've also used the Tailwind colors for the new design, so it would be easy to implement it if you decide so.

If interested, I can provide more info about the design (colors, spacing, sizes, font...) and possibly even help with the implementation.

Thanks for reading!

**Comment by the-abe-train** [comment]
Hi there!

This redesign is really cool. I really like the interwoven clouds in the background and the 3D buttons. I appreciate that you took the time to put this together, but at the moment, I don't feel that a redesign is necessary for the game. That said, I'd be down to collaborate on a new project together! If you're interested, or have any ideas for a new web app or game, reach out to me on [Twitter](https://twitter.com/theAbeTrain) or through my [website](https://the-abe-train.com).

Thanks!
