### ISSUE TITLE
Andaman and Nicobar Islands (part of India) are not highlighted correctly

### ISSUE THREAD

**Issue by SIVAH-AKASH** [the-abe-train/globle#50]
Only a part of the Andaman and Nicobar islands are highlighted when I enter India.

**Comment by the-abe-train** [comment]
Getting a high level of precision and accuracy is challenge with a lot of small islands in the game. So, while you are correct, more detailed polygons for Andaman and Nicobar islands are not feasible.

**Comment by SIVAH-AKASH** [comment]
Thanks for helping me realize this. I do not have much experience with programming or GitHub, but I did find what seems to be source data for the polygons and updated it in #82.
