### ISSUE TITLE
Banned from Facebook

### ISSUE THREAD

**Issue by olliechick** [the-abe-train/globle#53]
The Globle URL has been banned from Facebook for spam. This could be partially solved by #10 - at least, the URL wouldn't be in the share text.

![Screenshot_20220320-084154](https://user-images.githubusercontent.com/6047072/159136302-3088f3a5-79a5-4d8d-b58f-c029278c14f0.png)

**Comment by the-abe-train** [comment]
You're right. I'll review #10 and change the share message this weekend.
