### ISSUE TITLE
Globle countries issue

### ISSUE THREAD

**Issue by GamerxIsCool** [the-abe-train/globle#57]
I was playing today globle and I tried U.S. and then I scrolled down to Antarctica and saw that it didn't register the countries claims in it now I know it says that y'all don't make small territories but it is pretty big

**Comment by SIVAH-AKASH** [comment]
I don't think that is officially recognized by the UN?

Also it is a "claim" with no proper settlements in the continent that powerful and regional countries have made, which is something that any country can make. I may be mistaken.

**Comment by the-abe-train** [comment]
Globle uses this framework to determine what is a country:
https://www.sporcle.com/blog/2013/01/what-is-a-country/

**Comment by SIVAH-AKASH** [comment]
I'm actually referring to the borders of a certain state within a country here.

This is a similar situation to the hypothetical scenario of Globle not highlighting half the Hawaiian islands when someone enters "USA".
________________________________
