### ISSUE TITLE
Error "Refused to execute script from '[...]chunk.js' because its MIME type ('text/html') is not executable, and strict MIME type checking is enabled."

### ISSUE THREAD

**Issue by wjandrea** [the-abe-train/globle#59]
Error when accessing the site results in a blank white page.

Tested on Chrome (desktop and mobile) and Firefox.

Full error message:
`Refused to execute script from 'https://globle-game.com/static/js/876.c3e81c58.chunk.js' because its MIME type ('text/html') is not executable, and strict MIME type checking is enabled.`

Results in an exception:
```
ChunkLoadError: Loading chunk 876 failed.
(error: https://globle-game.com/static/js/876.c3e81c58.chunk.js)
    at Object.t.f.j (jsonp chunk loading:27:18)
    at ensure chunk:6:25
    at Array.reduce (<anonymous>)
    at Function.t.e (ensure chunk:5:56)
    at Auxilliary.tsx:13:31
    at I (react.production.min.js:18:52)
    at qo (react-dom.production.min.js:269:22)
    at vu (react-dom.production.min.js:250:347)
    at Su (react-dom.production.min.js:250:278)
    at bu (react-dom.production.min.js:250:138)
```

**Comment by scottBowles** [comment]
I got the same. Chrome loads the front page, but after clicking the globe to play it crashes.

In the console: https://pastebin.com/3BEk2KBL

**Comment by the-abe-train** [comment]
Hey there, I think I fixed this issue. Can you both try again and let me know?

**Comment by scottBowles** [comment]
Works for me! Thanks for the awesome game!

**Comment by wjandrea** [comment]
Yup, works now!
