### ISSUE TITLE
Colour changes after viewing help

### ISSUE THREAD

**Issue by jimmyjudas** [the-abe-train/globle#6]
Today, my 3rd guess was quite close (reddish). I then clicked on the help and clicked on the globe to get back to the game. The 3rd country had suddenly turned a peach colour (i.e. looked like a guess that wasn't so close). I could then play on fine and in fact the answer bordered the country in question, but clearly something went wrong with the colour changing. I have a screenshot I can share after today to avoid spoilers!

Thanks for the great game though!

**Comment by the-abe-train** [comment]
Hi Jimmy! 

Thank you for playing, and for bringing this to my attention. Can you send me a screenshot on Twitter? @theAbeTrain

(Is it possible to send a DM on GitHub? If so, you can do that instead).

**Comment by murdocha** [comment]
Same/similar issue for me. The ranking Gradient colors are no longer correct after clicking away. I _think_ it might have been after clicking the help icon.

Apparently no DMs in Github anymore. 

And you should check this out.
Not really a Github privacy lapse, but a “feature” of Git itself? 
From: https://stackoverflow.com/a/44229207 Leanne’s comment there has a solution to prevent _future leaks_ but not sure that helps with earlier commit history…

**Comment by the-abe-train** [comment]
The issue has been resolved. Thank you all for pointing it out and helping me identify it; it was indeed related to viewing the help screen.

**Comment by jimmyjudas** [comment]
Thanks!
