### ISSUE TITLE
Globle - Lesotho South Africa 

### ISSUE THREAD

**Issue by Al4nH** [the-abe-train/globle#66]
Hi . Globle told me South Africa was about 150km from the answer, which was Lesotho. How can that be?

**Comment by vitorhugods** [comment]
@Al4nH My game was a bit ruined by this too, but once I underrstood what was going on, I managed to hit the right place.

My understadning is that the game only considers the external borders of South Africa.

So it is calculating this border:
![grafik](https://user-images.githubusercontent.com/9389043/160920358-6c5055e1-87c9-4d52-a0e8-f86c16062b2b.png)

I am inclined to think that this may be a generalised issue with all enclaves.

**Comment by vitorhugods** [comment]
Nevermind.

I see that it was fixed yesterday: https://github.com/the-abe-train/globle/commit/cb103cb1c935d109627b188643d3dc9d827be273.
