### ISSUE TITLE
Improvement: Generate desktop/mobile messages in a consistent way

### ISSUE THREAD

**Issue by Israel77-dev** [the-abe-train/globle#68]
I was translating the game messages to portuguese when I noticed some inconsistencies on the way different text for mobile and desktop is handled. Specifically text telling the reader to either "Tap" (on mobile) or "Click" (on desktop).

## The good approach ✅

For example, in message Aux1 from en-CA.ts (or other localized messsage file), the difference is handled by having a tuple containing the strings to be shown on the message in each context:
```typescript
export const English: Messages = {
  ...
  Aux1: `<b>["Click", "Tap"]</b> [...]`
  ...
}
```
This array is later parsed by a function in the React component used to render the message, and only the suitable string for each context is shown on the actual message.

I found this first approach really neat, and it is great for translators, since we only need to follow the same pattern and translate the strings inside the array in order to get the desired result on the language we are translating to.

## The bad approach ❌

Unfortunately, this solution is not used throghout the entire codebase. For example, in the same file on message Game4, we found a different approach for generating the messages. An interpolated variable is used instead:

```typescript
export const English: Messages = {
  ...
  Game4: `[...] {click} [...]` 
  ...
}
```
This variable is hardcoded on the Message component to assume the value of either "tap" or "click" depending on the device the app is running. In my opinion this is a bad solution on the long term because it makes impossible for translators to translate this string without tweaking with parts of the codebase that should not be touched when you're only translating, which is far from ideal.

I suggest changing all the messages to use the first approach, and making all components handle it properly. This is a design decision that should be made early on, so we can standardize the messages and the way they're written before other translators use them.

**Comment by the-abe-train** [comment]
With the Spanish translations, I was kind of making up my method as I went, so it's actually quite nice to hear from another developer what worked and what didn't. I will make the change and close this issue on my next update, probably next weekend. I appreciate the code review!

**Comment by the-abe-train** [comment]
Pushing this change on the next update. Thanks again!
