### ISSUE TITLE
distance from romania to canada seems off

### ISSUE THREAD

**Issue by cptjack94** [the-abe-train/globle#70]
Hi, first off I wanna say i greatly enjoy your game! However today when I was trying to figure out the country I started with romania and it said I was 4650kms away from the country, after a couple of guesses I got to iceland which was 1650kms away. Feeling very stumped I used a radius calculator online to see where the two intersect and I found that romaina and iceland didn't overlap any land. I guessed canada because that was closest to iceland and got it right, but romaina is about 500km short of any land. Is this a bug or are you using international waters boundary, or am i just missing something? Thanks

**Comment by the-abe-train** [comment]
Hi there. The distance calculation in Globle is the shortest distance between borders along the Earth's surface. Below is a picture of what that looks like between Romania and Canada.

![image](https://user-images.githubusercontent.com/47761569/162270738-946ba8f6-473c-4953-ac02-6c6377248845.png)
