### ISSUE TITLE
England

### ISSUE THREAD

**Issue by Tekoa80** [the-abe-train/globle#71]
Why is "England" not a valid country?

**Comment by olliechick** [comment]
It's part of the UK

**Comment by Tekoa80** [comment]
Yes, but the "UK" is not a country, it's a collection of countries.

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by olliechick** [comment]
From the readme:
> The list of countries for this game is the same as that used by [Sporcle](https://www.sporcle.com/blog/2013/01/what-is-a-
country/)

See that link for why England is not included
