### ISSUE TITLE
Typo for São Tomé and Príncipe

### ISSUE THREAD

**Issue by Onemillionbilliontrillion** [the-abe-train/globle#75]
In the globle game you have put "São Tomé and Principe. The country has an acute accent on the first I. You are allowed to enter the country name without the accents but on the message saying I was correct it was spelled incorrectly. 
There is also a typo for Eswatini. On the win message it says "The Mystery Country is eSwatini[sic]!"

**Comment by the-abe-train** [comment]
Fixed for next update!
