### ISSUE TITLE
Idea/suggestion - could we add "Distance Unit: KM / Mile" in the Settings?

### ISSUE THREAD

**Issue by rhw168** [the-abe-train/globle#91]
I find it distracting that I had to do the mental conversion of KMs to miles when I was concentrating in placing a circle with the radius of the given distance from my guessed country.

Let's remove the need for the player to go thru that extra mental processing layer while playing this game.
Let's provide the user with a choice of distance unit that is more in tune with the player.

**Comment by filbo** [comment]
As I commented in another issue ... I see no indicators of either KM or Mi on my screen!  Can someone post a screenshot of what I'm missing?

**Comment by rhw168** [comment]
Here you go @filbo - snap today's screen and circled the "distance ... KM" (at the bottom of the screen)
![bloble-km](https://user-images.githubusercontent.com/59745107/171929585-79efdbe6-2e28-4ce3-a941-b928e9f65e70.png)
.

**Comment by rhw168** [comment]
Thanks! (Did not even notice that slider.)
