### ISSUE TITLE
Globle - Philippines

### ISSUE THREAD

**Issue by DOsoyoos** [the-abe-train/globle#94]
Nothing comes up on Globle for the Philippines. I’ve tried The Philippines, Philippines, Republic of the Philippines or The Republic of the Philippines. Thx!

**Comment by olliechick** [comment]
I just tried "Philippines" and it worked

**Comment by DOsoyoos** [comment]
I’ll try again tomorrow. But I keep getting ‘invalid country’ when I put in
Philippines. Hmmm.

**Comment by DOsoyoos** [comment]
Philippines was my first guess today…and it worked!
