### ISSUE TITLE
Bosnia and Herzegovina

### ISSUE THREAD

**Issue by SuperCoolDude** [the-abe-train/globle#95]
Please accept "Bosnia" as an answer for this, as it is common nomenclature, or also accept the official abbreviations of B&H or BiH. Most English speakers just refer to the country as "Bosnia" even though it is officially Bosnia and Herzegovina.

**Comment by olliechick** [comment]
this would be fixed by #56

**Comment by SuperCoolDude** [comment]
That doesn't include the official accepted abbreviations of BiH or B&H. Currently can only accept Bosnia and Herzegovina.

**Comment by the-abe-train** [comment]
Added Bosnia as an alternative name.
