### ISSUE TITLE
Zimbabwe and Namibia

### ISSUE THREAD

**Issue by rbharris1** [the-abe-train/globle#98]
For today's mystery country, I guessed Zimbabwe and it showed the darkest red color. However, Zimbabwe doesn't share a border with Namibia. 
![Screenshot_20220525-082958](https://user-images.githubusercontent.com/16739494/170262876-9a1bbf22-7234-48ec-955f-fdf301583eff.png)

Love the game, though!

**Comment by escalonn** [comment]
the distance is only 150 meters, which would show the same color as 0 meters, and rounds to the 0 km displayed on the interface, so i don't think there's a bug here. there's not a specially different color for adjacent countries, it's a continuous spectrum through e.g. 100km, 50km, 0km.

**Comment by the-abe-train** [comment]
The distance is too small to have a meaningfully distinct colour difference.
