### ISSUE TITLE
Israel's borders

### ISSUE THREAD

**Issue by B1obfish123** [the-abe-train/globle#99]
According to the game,
Israel - Palestine = 1 km 
and
Israel - Egypt = 13 km,
which both should be 0 km

**Comment by epixian** [comment]
Similarly, according to the game,
Egypt - Jordan = 45km (actual <10km)

**Comment by the-abe-train** [comment]
These issues arise from the game's borders not being perfectly precise or accurate. I'm pushing an update in the next day or so that just rounds borders to the nearest 50 km or 50 miles.
